name: Patch build and release

on:
  workflow_call:
    inputs:
      app:
        type: string
        required: true
    secrets:
      UESIO_CLI_USERNAME:
        required: true
      UESIO_CLI_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: "npm"
      - name: Setup Uesio CLI Symlink
        shell: bash
        run: |
          # Symlink the Uesio CLI for subsequent use
          wget -q https://docs.ues.io/site/files/uesio/docs/v1.1.3/clilinux
          chmod +x clilinux
          sudo ln -s $PWD/clilinux /usr/local/bin/uesio
      - name: NPM install top level
        shell: bash
        run: npm ci
      - name: Build, deploy, and package app
        shell: bash
        env:
          UESIO_CLI_USERNAME: ${{ secrets.UESIO_CLI_USERNAME }}
          UESIO_CLI_PASSWORD: ${{ secrets.UESIO_CLI_PASSWORD }}
          UESIO_CLI_HOST: ${{ vars.UESIO_CLI_HOST }}
          UESIO_CLI_LOGIN_METHOD: uesio/core.platform
        run: |
          echo "Building ${{ inputs.app }}"
          cd apps/${{ inputs.app }}
          npm ci
          npm run lint
          cd - >> /dev/null
          bash bundle.sh apps/${{ inputs.app }}
